### PR TITLE
Improve filter sliders.

### PR DESCRIPTION
**Pull request by DeKleineKobini**
- [x] Allow keyboard movement to the slider.
- [ ] Include current values in function itself.
- [x] Fix code to properly use the minimum value for the slider.
- [x] Some other minor tweaks as well.
  - [x] Better function order.
  - [x] Explicitly define limits, including the level 1 minimum instead of 0.

### CODE REVIEW

**Comment by DeKleineKobini** [comment]
"Fix code to properly use the minimum value for the slider." not sure how I would be able to do this

**Comment by Sashank999** [comment]
> "Fix code to properly use the minimum value for the slider." not sure how I would be able to do this

What did you want to do actually ?

**Comment by DeKleineKobini** [comment]
> > "Fix code to properly use the minimum value for the slider." not sure how I would be able to do this
> 
> What did you want to do actually ?

Sometimes dragging isn't precise enough, so I want to allow left and right arrow control. That in itself is working already, but I can't get the bar updating right because of the minimal value of 1.

**Comment by DeKleineKobini** [comment]
- Left and right can now switch sides. This prevents them from getting stuck when they are the same value.
- Instead of the value being linked to a specific handle, it now is updated on the global slider.
- Instead of the html being generated by a different function, it's now inside of the class.
- [ ] Keyboard controls are a bit off right now when switching sides.
- [ ] I still have to update the features that use a filter.
  - [x] Jail
  - [ ] Abroad people
  - [ ] Hospital

**Pull request merged**
